FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /build
COPY . .
RUN mvn clean package -e

FROM openjdk:17.0.2-jdk
WORKDIR /app
COPY --from=build /build/target/LearnEnglish-0.0.1-SNAPSHOT.jar /app/application.jar
COPY --from=build /build/src/main/resources/application.yml /app/application.yml
ENTRYPOINT ["java","-jar","/app/application.jar","--spring.config.location=/app/application.yml"]
